/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated user's profile.
         * @description Email, status, when the account was created, and whether a TOTP second
         *     factor is enrolled and confirmed.
         *
         *     There is nothing else, because migration 00005 stores nothing else: no
         *     legal name, no address, no date of birth, no document, no country, no
         *     jurisdiction. Their absence is a design decision recorded in that
         *     migration, not an unimplemented field.
         */
        get: operations["getAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The authenticated user's derived play-money balance.
         * @description **The balance is DERIVED, never stored.** It is `sum(amount_minor)` over
         *     the user's ledger entries, read through the `account_balances` view.
         *     There is no balance column anywhere in the schema and migration 00006
         *     makes that a structural fact rather than a convention: a stored balance
         *     can be stale, and a bet slip validated against a stale balance is an
         *     overdraft.
         *
         *     Two accounts are reported. `cash` is spendable; `escrow` holds the stakes
         *     of open wagers, which have left the spendable balance but have not yet
         *     been won or lost. Their sum is the user's total position.
         *
         *     A user with no ledger movement yet returns zero balances with
         *     `entry_count: 0` -- correctly, and without inventing a grant. "This
         *     account was touched and nets to nothing" and "this account has never been
         *     touched" are different facts, and `entry_count` is what distinguishes
         *     them.
         *
         *     If this fold ever becomes too slow the answer is a MATERIALISED VIEW
         *     refreshed from the ledger, never a mutable column on `users`: a
         *     materialised view can be provably rebuilt from the entries, a column
         *     cannot.
         */
        get: operations["getBalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The self-imposed limits currently in force.
         * @description Responsible-gaming-style self-imposed limits (CLAUDE.md section 6). The
         *     current limit for a `(kind, period)` pair is the one row with no
         *     `superseded_at`; superseded rows are history and are not returned here.
         *
         *     There is no `deposit` limit and there will not be one: this system has no
         *     deposits. The play-money analogue is `grant`, which binds to the ledger
         *     entry kind of the same name -- the only way money enters a balance.
         */
        get: operations["listLimits"];
        put?: never;
        /**
         * Set or change a self-imposed limit.
         * @description **Tightening binds immediately. Loosening serves a cooling-off period.**
         *     That asymmetry is the entire point of the control: a limit a user can
         *     lift the instant they want to is not a limit. A request that lowers a
         *     money limit, shortens a session limit, or introduces a limit where there
         *     was none takes effect at `requested_at`; a request that raises or removes
         *     one takes effect after the cooling-off period and the response reports
         *     the `effective_from` instant so the user can see when.
         *
         *     Rows are append-only history, never edited: the previous row is closed
         *     with `superseded_at` and a new one is written. "What limit was in force
         *     when this wager was accepted" must remain answerable, and an operator
         *     must not be able to make a customer's limit history disappear -- the
         *     database refuses both an UPDATE of the substantive columns and a DELETE.
         *
         *     Audited: writes `user_limit.set` to the audit log with the before and
         *     after state.
         */
        post: operations["setLimit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Begin TOTP enrolment.
         * @description Mints a shared secret, stores it as AEAD ciphertext under a key held
         *     outside the database, and returns the provisioning URI ONCE. The secret
         *     is not retrievable afterwards; a lost enrolment is restarted, not
         *     recovered.
         *
         *     The enrolment is NOT active until `/account/totp/confirm` proves a code
         *     from it. An unconfirmed row must never be treated as an enrolled second
         *     factor -- otherwise a mis-scanned QR code locks the account out.
         *
         *     Audited: `totp.enrol_begin`. The provisioning URI is never logged.
         */
        post: operations["beginTOTPEnrolment"];
        /**
         * Remove the TOTP second factor.
         * @description Requires a currently-valid code from the factor being removed, so that a
         *     stolen access token alone cannot strip the second factor.
         *
         *     Audited: `totp.remove`.
         */
        delete: operations["removeTOTP"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/account/totp/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Prove a code and activate the TOTP second factor.
         * @description Audited: `totp.enrol_confirm`. The code is never logged.
         */
        post: operations["confirmTOTPEnrolment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange credentials for an access token and a refresh token.
         * @description **This endpoint does not enumerate users.** An unknown address and a
         *     wrong password produce byte-identical responses, the same status code,
         *     and the same timing: the handler runs a full argon2id verification
         *     against a fixed decoy hash when no user is found, so the expensive path
         *     is taken either way.
         *
         *     If the account has a confirmed TOTP enrolment, a first call without
         *     `totp_code` returns `401` with `code: totp_required`. That response is
         *     only reachable AFTER the password has been verified, so it discloses
         *     nothing to someone who does not already hold the password.
         *
         *     On success a new refresh-token FAMILY is started. The refresh token is
         *     returned once, in this response body, and never again; only its SHA-256
         *     reaches the database.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke the presented refresh token's entire family.
         * @description Revokes the family with reason `logout`, which ends every session
         *     descended from that login. Idempotent: logging out an already-revoked or
         *     unknown family returns `204`, because reporting "that token was already
         *     dead" is an enumeration oracle and there is nothing a caller can do with
         *     the distinction.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate a refresh token for a new access token.
         * @description Redeeming a refresh token invalidates it and issues its successor, in one
         *     transaction. At any instant a family has exactly one live token.
         *
         *     **Reuse detection.** Presenting a token that has already been redeemed
         *     means either an attacker is replaying a stolen token or the legitimate
         *     client is replaying one whose successor was stolen. The two are
         *     indistinguishable, so the only safe response is to revoke the ENTIRE
         *     family -- every descendant of the original login -- with reason
         *     `reuse_detected`, and force a fresh password authentication. The
         *     response is `401`, identical to the response for an unknown token: a
         *     thief must not learn from the status code that they tripped a detector.
         *
         *     The detection is structural, not a read-then-write: a partial unique
         *     index (`refresh_tokens_one_successor`) permits at most one child per
         *     token, so two concurrent redemptions of the same token cannot both mint
         *     a successor whatever the application believed it read.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account.
         * @description Email and password only. There is no name, no address, no date of birth
         *     and no identity document, because CLAUDE.md section 0 rules out KYC
         *     entirely and migration 00005 has no column to put any of them in.
         *
         *     The password is hashed with argon2id and the full PHC parameter string is
         *     stored, so the cost can be raised later and rehashed per user on their
         *     next successful login without a migration.
         *
         *     A play-money grant is NOT issued here. Money enters a balance only
         *     through a double-entry ledger transaction, which is phase 8.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The live odds board across every league.
         * @description Tradeable events (`scheduled`, `live`, `suspended`) starting before
         *     `starting_before`, soonest first, with the current best price on each
         *     event's main markets.
         *
         *     **Where this reads from.** Events and their market tree come from
         *     Postgres, which is the source of truth for the catalogue. Prices come
         *     from the `prices` hypertable through a bounded window
         *     (`LatestPriceForEachBookOnSelections`), which is a `DISTINCT ON` served
         *     entirely by `prices_natural_key_idx`. Redis fronts that read as a
         *     snapshot cache; a miss falls through to Postgres and the answer is
         *     identical either way, because CLAUDE.md section 3 makes Redis "never
         *     the source of truth". A suspended market is returned with
         *     `status: suspended` rather than hidden, because a suspension is usually
         *     seconds long and dropping the row would make the board flicker.
         *
         *     **Staleness.** Every price carries `observed_at` (the provider's own
         *     instant) and `ingested_at` (when this system received it). Their
         *     difference is the provider-attributable share of the staleness SLO;
         *     `now() - observed_at` is total staleness. The API does not editorialise
         *     either number.
         */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every sportsbook whose lines are ingested.
         * @description Reads Postgres (`books`). Single page: bounded by the catalogue.
         *
         *     `kind` and `is_reference` are both returned. A quote from a book of kind
         *     `synthetic` is a statement about a random number generator and a client
         *     MUST be able to label it as such; `is_reference` names the sharp book the
         *     pricer devigs against, which is the baseline every EV number is relative
         *     to.
         */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One event with its full market tree.
         * @description The event detail page: the event, its league and sport breadcrumb, every
         *     market on it, every selection under each market, and the current price
         *     from every quoting book on every selection.
         *
         *     Selections are returned in `domain.SelectionRole.DisplayOrder()` --
         *     home, draw, away, over, under, outright -- which is not the
         *     lexicographic order of those strings and therefore cannot be produced by
         *     any SQL `ORDER BY`. The API sorts them so that every client renders the
         *     same tree.
         *
         *     Not paginated: an event's market tree is bounded by the event.
         */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/leagues/{leagueSlug}/board": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The live odds board for one league.
         * @description Identical to `/board` but scoped to a league, and served by a different
         *     index (`events_league_board_idx`) because a cross-league query cannot use
         *     an index led by `league_id`.
         */
        get: operations["getLeagueBoard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/markets/{marketId}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Multi-book comparison for one market.
         * @description Every book's current price on every selection of one market, plus the
         *     best price per selection and the market's overround at each book.
         *
         *     This is the endpoint behind CLAUDE.md section 6's "multi-book
         *     comparison". The overround is computed here rather than stored: it is a
         *     pure function of the quotes returned in the same response
         *     (`odds.Overround`), so a client can check the arithmetic, and a stored
         *     copy would be a second truth able to disagree with the prices beside it.
         *
         *     Not paginated: bounded by (selections on a market) x (books ingested).
         */
        get: operations["compareMarketPrices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Find tradeable events by competitor name prefix.
         * @description Case-insensitive PREFIX match on either competitor's name, served by two
         *     partial expression indexes (`events_{home,away}_competitor_search_idx`,
         *     both `lower(col) text_pattern_ops`). Infix search would need a GIN
         *     trigram index and the `pg_trgm` extension, which migration 00002
         *     deliberately does not create; a type-ahead box wants prefix matching
         *     anyway.
         *
         *     The status set here is NARROWER than the board's: `scheduled` and `live`
         *     only, which is exactly `domain.EventStatus.AcceptsWagers()`. The board
         *     shows a suspended event greyed out because a suspension is seconds long;
         *     this endpoint answers "what can I bet on", and a suspended market cannot
         *     be bet on. The accepted consequence is that an event is unfindable during
         *     a suspension.
         */
        get: operations["searchEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/selections/{selectionId}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Line movement for one selection at one book.
         * @description The reason the `prices` hypertable exists. Returns every quote one book
         *     made on one selection inside a half-open window `[from, to)`, oldest
         *     first, optionally downsampled.
         *
         *     **The window is REQUIRED and is not a convenience.** `prices` is
         *     partitioned on `observed_at` in 12-hour chunks and migration 00004
         *     installs no retention policy, so the chunk count grows for the life of
         *     the deployment. A read with no lower bound defeats chunk exclusion and
         *     makes the planner consult an index on every chunk that has ever existed.
         *     There is deliberately no unbounded variant to reach for by accident.
         *     `to` defaults to now; `from` has no default and must be supplied.
         *
         *     **Downsampling.** `resolution` selects a Timescale `time_bucket` width.
         *     `raw` returns every stored quote and is what a five-minute window wants;
         *     anything longer wants a bucket, because a market quoted every two seconds
         *     for a week is 300k points and no chart can draw them. A bucketed point
         *     reports `open`, `high`, `low`, `close` and `samples` for the bucket
         *     rather than a mean: the mean of a line is not a line anyone traded at,
         *     and open/close is what CLV and steam detection are computed from.
         *
         *     `max_points` is a guard, not a page size -- a request whose window and
         *     resolution would exceed it is rejected `422` with the resolution that
         *     would fit, rather than being silently truncated into a chart that lies
         *     about where the line ended.
         */
        get: operations["getSelectionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every sport in the catalogue.
         * @description Reads Postgres (`sports`). Single page: the row count is the number of
         *     sports the provider covers, which is single digits.
         */
        get: operations["listSports"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sports/{sportSlug}/leagues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The leagues under one sport.
         * @description Reads Postgres (`leagues`, index `leagues_sport_idx`). Single page:
         *     bounded by the catalogue.
         */
        get: operations["listLeaguesInSport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The whole profile. There is no name, address, date of birth, document,
         *     country or jurisdiction field, because this is not a licensed sportsbook
         *     and no such column exists (migration 00005). Their absence is deliberate.
         */
        Account: {
            /** Format: date-time */
            created_at: string;
            email: components["schemas"]["EmailAddress"];
            id: components["schemas"]["EntityID"];
            status: components["schemas"]["AccountStatus"];
            /** @description True only for a CONFIRMED enrolment. An unconfirmed one is not a second factor. */
            totp_enrolled: boolean;
        };
        AccountBalance: {
            /** @enum {string} */
            account_kind: "user_cash" | "user_escrow";
            balance_minor: components["schemas"]["MoneyMinor"];
            /**
             * Format: int64
             * @description Ledger entries folded to produce this balance. Zero means the account
             *     has never moved -- a different fact from "moved and nets to zero",
             *     and the only thing that distinguishes them.
             */
            entry_count: number;
        };
        /** @enum {string} */
        AccountStatus: "active" | "suspended" | "self_excluded" | "closed";
        BalanceResponse: {
            /** Format: date-time */
            as_of: string;
            cash: components["schemas"]["AccountBalance"];
            /**
             * @description Not a real currency and deliberately not an ISO 4217 code. Labelling
             *     play money `USD` is the first step toward a client treating it as
             *     money, which CLAUDE.md section 0 forbids.
             * @enum {string}
             */
            currency: "PLAY";
            escrow: components["schemas"]["AccountBalance"];
            /**
             * Format: int32
             * @description Divide by this only for DISPLAY. Never do arithmetic in major units.
             * @enum {integer}
             */
            minor_units_per_major: 100;
            /** @description cash + escrow. The user's total position. */
            total_minor: components["schemas"]["MoneyMinor"];
        };
        BestPrice: {
            book_id: components["schemas"]["EntityID"];
            book_slug: components["schemas"]["Slug"];
            decimal_odds: components["schemas"]["DecimalOdds"];
            display?: string;
            /** Format: date-time */
            observed_at: string;
            role: components["schemas"]["SelectionRole"];
            selection_id: components["schemas"]["EntityID"];
        };
        BoardEntry: {
            event: components["schemas"]["EventSummary"];
            /** @description The event's markets with their selections and current prices. */
            markets: components["schemas"]["Market"][];
        };
        BoardPage: {
            /**
             * Format: date-time
             * @description When this page was assembled. A client computes staleness against
             *     this rather than against its own clock, so a skewed browser clock
             *     cannot make a fresh board look stale.
             */
            as_of: string;
            data: components["schemas"]["BoardEntry"][];
            page: components["schemas"]["PageInfo"];
        };
        Book: {
            id: components["schemas"]["EntityID"];
            /**
             * @description The sharp book the pricer devigs against to produce fair value. Every
             *     EV number in this system is relative to this book, so a client that
             *     renders EV must be able to name it.
             */
            is_reference: boolean;
            kind: components["schemas"]["BookKind"];
            name: string;
            slug: components["schemas"]["Slug"];
        };
        /**
         * @description Exactly `domain.BookKind`. `synthetic` is the in-house stochastic market
         *     maker: a quote from it is a statement about a random number generator and
         *     every surface that renders one must be able to label it as such.
         * @enum {string}
         */
        BookKind: "external" | "synthetic";
        BookPage: {
            data: components["schemas"]["Book"][];
            page: components["schemas"]["PageInfo"];
        };
        BookQuote: {
            book_id: components["schemas"]["EntityID"];
            book_kind: components["schemas"]["BookKind"];
            book_name: string;
            book_slug: components["schemas"]["Slug"];
            is_reference: boolean;
            /**
             * Format: double
             * @description `sum(1/decimal_odds) - 1` over this book's quotes on the market --
             *     the book's margin. Null when the book has not quoted every selection,
             *     because an overround computed over a partial market is not a margin,
             *     it is a smaller number that looks like a better price.
             */
            overround?: number | null;
            quotes: components["schemas"]["SelectionQuote"][];
        };
        Competitor: {
            id?: components["schemas"]["EntityID"];
            name: string;
        };
        /**
         * Format: double
         * @description Decimal odds -- the total return per unit staked, stake included. THE
         *     CANONICAL representation. American and fractional are derived and lossy.
         * @example 1.909
         */
        DecimalOdds: number;
        /**
         * @description An email address.
         *
         *     The pattern is EXACTLY the database's `users_email_shape` CHECK -- one
         *     `@` with non-empty, whitespace-free sides -- and no tighter. Stricter
         *     regexes reject deliverable addresses (quoted local parts, single-label
         *     domains) and the only real proof an address exists is sending mail to it.
         *
         *     Deliberately NOT `format: email`. That format makes oapi-codegen emit
         *     `openapi_types.Email`, which drags github.com/oapi-codegen/runtime into a
         *     module whose serving path otherwise has no third-party dependency at all,
         *     in exchange for a type alias over `string` that validates nothing at
         *     runtime. The pattern above is the validation, it is the same one the
         *     database enforces, and it costs nothing.
         *
         *     Stored lowercase-normalised; the database CHECK makes that an invariant
         *     rather than a convention, so a plain unique index is a correct
         *     case-insensitive uniqueness constraint.
         * @example sharp@example.test
         */
        EmailAddress: string;
        /**
         * @description A domain identifier. The charset is exactly `domain.validID`: `:` is
         *     excluded because WebSocket channels are `event:{id}` and a colon inside
         *     an identifier would make splitting a channel name ambiguous.
         * @example evt_nfl_2026_w1_kc_buf
         */
        EntityID: string;
        /**
         * @description THE ONE ERROR SHAPE. Every non-2xx response in this API has exactly this
         *     body, so a client writes one decoder and one branch.
         *
         *     `code` is a stable machine-readable token and is what a client should
         *     switch on; the HTTP status is a coarser classification of the same fact.
         *     `message` is a fixed human-readable string chosen from a closed set in
         *     Go. It is NEVER an error value, a driver message, a SQLSTATE, a stack
         *     frame, a file path or a query -- an error body is an untrusted output
         *     surface and everything a caller must not learn is logged under
         *     `request_id` and dropped here.
         *
         *     `invalid_params` is present only for `400` and `422` and names the
         *     offending parameters so a form can highlight them. Its `reason` strings
         *     are equally fixed.
         */
        Error: {
            /** @enum {string} */
            code: "bad_request" | "invalid_parameter" | "invalid_cursor" | "unauthenticated" | "invalid_credentials" | "totp_required" | "invalid_totp_code" | "forbidden" | "account_not_active" | "not_found" | "conflict" | "already_exists" | "unprocessable" | "rate_limited" | "internal";
            invalid_params?: components["schemas"]["InvalidParam"][];
            message: string;
            /**
             * @description Correlates this response with the server log line and the trace span
             *     that produced it. Quote it in a bug report; it is the only handle on
             *     what actually happened.
             */
            request_id: string;
        };
        EventDetail: {
            /** Format: date-time */
            as_of: string;
            event: components["schemas"]["EventSummary"];
            league: components["schemas"]["League"];
            markets: components["schemas"]["Market"][];
            sport: components["schemas"]["Sport"];
        };
        /**
         * @description Exactly `domain.EventKind`. `match` is a contest between two competitors;
         *     `outright` is a competition resolved among many runners and has no home
         *     or away side at all -- not empty ones.
         * @enum {string}
         */
        EventKind: "match" | "outright";
        /**
         * @description Exactly `domain.EventStatus`, same spelling, same members. The API does
         *     not get to invent a status the domain cannot represent, and the domain
         *     does not get to add one without changing this list.
         * @enum {string}
         */
        EventStatus: "scheduled" | "live" | "suspended" | "ended" | "settled" | "postponed" | "cancelled";
        EventSummary: {
            away_competitor?: components["schemas"]["Competitor"];
            clock?: components["schemas"]["GameClock"];
            home_competitor?: components["schemas"]["Competitor"];
            id: components["schemas"]["EntityID"];
            kind: components["schemas"]["EventKind"];
            league_id: components["schemas"]["EntityID"];
            name: string;
            /**
             * Format: date-time
             * @description The provider instant this event's state was observed at.
             */
            observed_at: string;
            /** Format: date-time */
            scheduled_start: string;
            score?: components["schemas"]["Score"];
            status: components["schemas"]["EventStatus"];
        };
        /** @description Live clock state. Absent entirely on an event that has not started. */
        GameClock: {
            /** Format: int64 */
            elapsed_seconds?: number | null;
            /** Format: int32 */
            period?: number | null;
            running: boolean;
        };
        /**
         * @description One point of a line-movement series. On `resolution: raw` every field but
         *     `samples` holds the same stored quote and `samples` is 1, so a client
         *     renders one shape whether or not it asked for downsampling.
         *
         *     Open/high/low/close rather than a mean: the mean of a line is a price
         *     nobody traded at, and CLV and steam detection are both computed from the
         *     endpoints of a window, not from its average.
         */
        HistoryPoint: {
            /**
             * Format: date-time
             * @description The bucket's start instant (`raw`: the quote's `observed_at`).
             */
            at: string;
            close: components["schemas"]["DecimalOdds"];
            close_display?: string;
            high: components["schemas"]["DecimalOdds"];
            /**
             * Format: double
             * @description The line at the bucket's close.
             */
            line?: number | null;
            low: components["schemas"]["DecimalOdds"];
            open: components["schemas"]["DecimalOdds"];
            /** Format: int32 */
            samples: number;
        };
        /**
         * @default raw
         * @enum {string}
         */
        HistoryResolution: "raw" | "10s" | "1m" | "5m" | "15m" | "1h" | "6h" | "1d";
        HistorySeries: {
            book_id: components["schemas"]["EntityID"];
            book_slug: components["schemas"]["Slug"];
            /**
             * Format: date-time
             * @description Inclusive.
             */
            from: string;
            points: components["schemas"]["HistoryPoint"][];
            /** @description The resolution actually applied. Equal to the one requested, or `raw` if none was. */
            resolution: components["schemas"]["HistoryResolution"];
            selection_id: components["schemas"]["EntityID"];
            /**
             * Format: date-time
             * @description Exclusive.
             */
            to: string;
        };
        InvalidParam: {
            /** @description The query parameter, path parameter or JSON pointer at fault. */
            name: string;
            reason: string;
        };
        League: {
            id: components["schemas"]["EntityID"];
            name: string;
            slug: components["schemas"]["Slug"];
            sport_id: components["schemas"]["EntityID"];
        };
        LeaguePage: {
            data: components["schemas"]["League"][];
            page: components["schemas"]["PageInfo"];
        };
        Limit: {
            /** @description Set on money kinds (`grant`, `stake`, `loss`); null on `session`. */
            amount_minor?: components["schemas"]["MoneyMinor"] | null;
            /**
             * Format: int32
             * @description Set on `session` only; null on money kinds.
             */
            duration_seconds?: number | null;
            /**
             * Format: date-time
             * @description Equal to `requested_at` for a tightening. Later for a loosening
             *     serving its cooling-off period.
             */
            effective_from: string;
            id: components["schemas"]["EntityID"];
            /** @description Whether `effective_from` has passed. A pending loosening is returned with `false`. */
            in_force: boolean;
            kind: components["schemas"]["LimitKind"];
            period: components["schemas"]["LimitPeriod"];
            /** Format: date-time */
            requested_at: string;
        };
        /**
         * @description Deliberately NOT `deposit`: this system has no deposits (CLAUDE.md
         *     section 0). `grant`, `stake` and `loss` are spelled identically to the
         *     ledger entry kinds they are evaluated against, so enforcing a limit is a
         *     sum filtered by the same string with no translation table in between.
         * @enum {string}
         */
        LimitKind: "grant" | "stake" | "loss" | "session";
        LimitPage: {
            data: components["schemas"]["Limit"][];
            page: components["schemas"]["PageInfo"];
        };
        /** @enum {string} */
        LimitPeriod: "day" | "week" | "month" | "session";
        LoginRequest: {
            email: components["schemas"]["EmailAddress"];
            password: string;
            /** @description Required only if the account has a confirmed TOTP enrolment. */
            totp_code?: string;
        };
        Market: {
            event_id: components["schemas"]["EntityID"];
            id: components["schemas"]["EntityID"];
            /** Format: double */
            line?: number | null;
            /** Format: date-time */
            observed_at: string;
            selections: components["schemas"]["Selection"][];
            status: components["schemas"]["MarketStatus"];
            /** @description The player a prop market is about. Null on every other market type. */
            subject?: string | null;
            type: components["schemas"]["MarketType"];
        };
        MarketComparison: {
            /** Format: date-time */
            as_of: string;
            /**
             * @description The best available price on each selection, and where it is. This is
             *     the input to arbitrage detection and it is computed here rather than
             *     left to the client so that "best" means one thing across every
             *     surface.
             */
            best: components["schemas"]["BestPrice"][];
            /** @description Every book quoting this market, ordered by slug. */
            books: components["schemas"]["BookQuote"][];
            market: components["schemas"]["MarketHeader"];
        };
        MarketHeader: {
            event_id: components["schemas"]["EntityID"];
            id: components["schemas"]["EntityID"];
            /** Format: double */
            line?: number | null;
            /** Format: date-time */
            observed_at: string;
            status: components["schemas"]["MarketStatus"];
            subject?: string | null;
            type: components["schemas"]["MarketType"];
        };
        /**
         * @description Exactly `domain.MarketStatus`.
         * @enum {string}
         */
        MarketStatus: "open" | "suspended" | "closed" | "settled" | "voided";
        /**
         * @description Exactly `domain.MarketType`.
         * @enum {string}
         */
        MarketType: "moneyline" | "spread" | "total" | "player_prop" | "futures";
        /**
         * Format: int64
         * @description An amount in MINOR UNITS (cents), as an integer. Never a float, never a
         *     string. The bound is 2^53-1, which is both the largest integer a float64
         *     holds exactly and JavaScript's `Number.MAX_SAFE_INTEGER`, and is the same
         *     bound the database CHECK constraints enforce -- so a JSON number is
         *     lossless for every value that can exist.
         * @example 250000
         */
        MoneyMinor: number;
        /**
         * @default decimal
         * @enum {string}
         */
        OddsFormat: "decimal" | "american" | "fractional";
        /**
         * @description Keyset pagination. There is no total count and there will not be one:
         *     counting an unbounded, continuously-written set costs a full scan on
         *     every page and the number is stale before it is serialised.
         */
        PageInfo: {
            has_more: boolean;
            /**
             * Format: int32
             * @description The page size actually applied, which may be smaller than the one requested.
             */
            limit: number;
            /**
             * @description Pass back as `cursor` for the next page. `null` when `has_more` is
             *     false. Opaque -- do not parse it.
             */
            next_cursor?: string | null;
        };
        Price: {
            book_id: components["schemas"]["EntityID"];
            book_slug: components["schemas"]["Slug"];
            decimal_odds: components["schemas"]["DecimalOdds"];
            /**
             * @description The price rendered in the requested `odds_format`. Present only when
             *     `odds_format` is `american` or `fractional`; `decimal_odds` above is
             *     always authoritative.
             */
            display?: string;
            /**
             * @description `1/decimal_odds`. WITH the book's vig still in it -- this is not a
             *     fair probability and must not be labelled as one in a UI. Returned
             *     because it is what a price cell's width or a bar chart is drawn from,
             *     and computing it client-side is one more place to get the reciprocal
             *     wrong.
             */
            implied_probability: components["schemas"]["Probability"];
            /**
             * Format: date-time
             * @description When this system received it. `ingested_at - observed_at` is the provider-attributable share of staleness.
             */
            ingested_at: string;
            /**
             * Format: double
             * @description The handicap or total this price was quoted at, when the market carries one.
             */
            line?: number | null;
            /**
             * Format: date-time
             * @description The provider's own instant. The subtrahend in the staleness SLO.
             */
            observed_at: string;
        };
        /** Format: double */
        Probability: number;
        RefreshRequest: {
            /**
             * @description The opaque refresh token from a previous session response. At least
             *     256 bits of `crypto/rand`; only its SHA-256 is stored, so a database
             *     leak yields no working tokens.
             */
            refresh_token: string;
        };
        RegisterRequest: {
            /** @description Normalised to lowercase before storage; the database CHECK makes that an invariant, not a convention. */
            email: components["schemas"]["EmailAddress"];
            /**
             * @description Minimum 12 characters and no composition rules. Length beats
             *     character-class requirements, which push users toward `Password1!`
             *     and toward reuse. Hashed with argon2id; never logged, never traced,
             *     never echoed.
             */
            password: string;
        };
        Score: {
            /** Format: int32 */
            away: number;
            /** Format: int32 */
            home: number;
        };
        SearchHit: {
            away_competitor_name?: string | null;
            home_competitor_name?: string | null;
            id: components["schemas"]["EntityID"];
            kind: components["schemas"]["EventKind"];
            league_id: components["schemas"]["EntityID"];
            name: string;
            /** Format: date-time */
            scheduled_start: string;
            status: components["schemas"]["EventStatus"];
        };
        SearchPage: {
            data: components["schemas"]["SearchHit"][];
            page: components["schemas"]["PageInfo"];
        };
        Selection: {
            best_price?: components["schemas"]["Price"];
            id: components["schemas"]["EntityID"];
            market_id: components["schemas"]["EntityID"];
            name: string;
            /**
             * @description The current price at each quoting book, ordered by book slug. Empty
             *     when no book has quoted this selection inside the freshness window --
             *     which is a correct answer, not a missing one.
             */
            prices: components["schemas"]["Price"][];
            role: components["schemas"]["SelectionRole"];
        };
        SelectionQuote: {
            decimal_odds: components["schemas"]["DecimalOdds"];
            display?: string;
            implied_probability: components["schemas"]["Probability"];
            /** Format: date-time */
            ingested_at: string;
            /** Format: double */
            line?: number | null;
            /** Format: date-time */
            observed_at: string;
            role: components["schemas"]["SelectionRole"];
            selection_id: components["schemas"]["EntityID"];
        };
        /**
         * @description Exactly `domain.SelectionRole`.
         * @enum {string}
         */
        SelectionRole: "home" | "draw" | "away" | "over" | "under" | "outright";
        /**
         * @description Returned by register, login and refresh. Both tokens are returned in the
         *     BODY and never set as cookies: this API is consumed cross-origin through
         *     a proxy by a Next.js client and by `pkg/client`, and a cookie-bearing
         *     API is a CSRF surface that would have to be defended with a second
         *     mechanism. The client stores the refresh token; the access token is held
         *     in memory.
         *
         *     **The refresh token is shown exactly once.** It is not retrievable
         *     afterwards and it does not appear in any log, span or metric.
         */
        SessionResponse: {
            /** @description Short-lived JWT. Present it as `Authorization: Bearer <token>`. */
            access_token: string;
            account: components["schemas"]["Account"];
            /**
             * Format: int32
             * @description Access-token lifetime in seconds. Minutes, not hours.
             */
            expires_in: number;
            /**
             * Format: date-time
             * @description Absolute end of the login lineage, measured from when the family
             *     STARTED, not from this token's issue. Without that, a session
             *     rotated every ten minutes would live forever.
             */
            refresh_expires_at: string;
            /** @description Opaque. Rotates on every use; reuse revokes the whole family. */
            refresh_token: string;
            /** @enum {string} */
            token_type: "Bearer";
        };
        /**
         * @description Exactly one of `amount_minor` and `duration_seconds` must be present, and
         *     which one is determined by `kind`: `session` takes a duration, every
         *     other kind takes an amount. The database enforces the same biconditional,
         *     so an impossible combination is unstorable as well as rejected.
         *
         *     Omitting both REMOVES the limit, which is a loosening and serves the
         *     cooling-off period like any other.
         */
        SetLimitRequest: {
            amount_minor?: components["schemas"]["MoneyMinor"] | null;
            /** Format: int32 */
            duration_seconds?: number | null;
            kind: components["schemas"]["LimitKind"];
            period: components["schemas"]["LimitPeriod"];
        };
        /** @example nfl */
        Slug: string;
        Sport: {
            id: components["schemas"]["EntityID"];
            name: string;
            slug: components["schemas"]["Slug"];
        };
        SportPage: {
            data: components["schemas"]["Sport"][];
            page: components["schemas"]["PageInfo"];
        };
        TOTPCodeRequest: {
            /** @description Compared in constant time against the expected code for the current and adjacent time steps. */
            code: string;
        };
        /**
         * @description Returned ONCE. The shared secret is never retrievable afterwards and is
         *     stored only as AEAD ciphertext under a key held outside the database,
         *     with the user id as additional authenticated data so a row copied between
         *     users fails to decrypt rather than silently granting the attacker's
         *     device the victim's second factor.
         */
        TOTPEnrolment: {
            /**
             * Format: date-time
             * @description An unconfirmed enrolment expires. A stale one must not linger as a half-enrolled factor.
             */
            expires_at: string;
            /**
             * @description `otpauth://totp/...`. CREDENTIAL MATERIAL -- it embeds the shared
             *     secret. Never logged, never traced, never persisted by a client
             *     beyond the moment the user scans it.
             */
            provisioning_uri: string;
        };
    };
    responses: {
        /** @description The request was malformed -- a bad parameter, an unparseable body, an unknown book slug, an undecodable cursor. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Something failed inside the service. The response carries a `request_id`
         *     and nothing else; the cause is in the logs and the trace under that id.
         */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No such entity. Never used to signal an authorization failure. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Rate limited. Limits are enforced per authenticated user AND per client
         *     IP, in Redis, so they hold across every replica rather than per pod.
         */
        TooManyRequests: {
            headers: {
                "RateLimit-Remaining"?: number;
                "RateLimit-Reset"?: number;
                /** @description Seconds to wait before retrying. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No access token, or one that failed verification. */
        Unauthorized: {
            headers: {
                /** @description `Bearer` with an error code, per RFC 6750. */
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /**
         * @description Syntactically valid but semantically impossible -- a `from` after its
         *     `to`, a window and resolution that exceed `max_points`, a session limit
         *     denominated in money.
         */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /**
         * @description Restrict prices to these books, by slug. Repeatable. Omitted means every
         *     book. An unknown slug is a `400`, not a silent empty result -- a typo
         *     that quietly returns nothing is the worst possible outcome for a price
         *     comparison.
         */
        BookFilter: components["schemas"]["Slug"][];
        /**
         * @description Opaque continuation token from a previous response's `page.next_cursor`.
         *     Do not construct or parse one. A cursor is bound to the ordering and the
         *     filters it was minted under and is rejected `400` if presented with
         *     different ones.
         */
        Cursor: string;
        EventID: components["schemas"]["EntityID"];
        LeagueSlug: components["schemas"]["Slug"];
        MarketID: components["schemas"]["EntityID"];
        /**
         * @description Adds a rendered `display` string to every price. `decimal_odds` is always
         *     present regardless, because it is the canonical value and the other two
         *     formats are lossy.
         */
        OddsFormatQuery: components["schemas"]["OddsFormat"];
        /** @description Maximum rows in this page. */
        PageLimit: number;
        SelectionID: components["schemas"]["EntityID"];
        SportSlug: components["schemas"]["Slug"];
        /**
         * @description Upper bound on `scheduled_start` (RFC 3339). Defaults to 24 hours from
         *     the time the request is served, which is "today's board".
         */
        StartingBefore: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAccount = components['schemas']['Account'];
export type SchemaAccountBalance = components['schemas']['AccountBalance'];
export type SchemaAccountStatus = components['schemas']['AccountStatus'];
export type SchemaBalanceResponse = components['schemas']['BalanceResponse'];
export type SchemaBestPrice = components['schemas']['BestPrice'];
export type SchemaBoardEntry = components['schemas']['BoardEntry'];
export type SchemaBoardPage = components['schemas']['BoardPage'];
export type SchemaBook = components['schemas']['Book'];
export type SchemaBookKind = components['schemas']['BookKind'];
export type SchemaBookPage = components['schemas']['BookPage'];
export type SchemaBookQuote = components['schemas']['BookQuote'];
export type SchemaCompetitor = components['schemas']['Competitor'];
export type SchemaDecimalOdds = components['schemas']['DecimalOdds'];
export type SchemaEmailAddress = components['schemas']['EmailAddress'];
export type SchemaEntityId = components['schemas']['EntityID'];
export type SchemaError = components['schemas']['Error'];
export type SchemaEventDetail = components['schemas']['EventDetail'];
export type SchemaEventKind = components['schemas']['EventKind'];
export type SchemaEventStatus = components['schemas']['EventStatus'];
export type SchemaEventSummary = components['schemas']['EventSummary'];
export type SchemaGameClock = components['schemas']['GameClock'];
export type SchemaHistoryPoint = components['schemas']['HistoryPoint'];
export type SchemaHistoryResolution = components['schemas']['HistoryResolution'];
export type SchemaHistorySeries = components['schemas']['HistorySeries'];
export type SchemaInvalidParam = components['schemas']['InvalidParam'];
export type SchemaLeague = components['schemas']['League'];
export type SchemaLeaguePage = components['schemas']['LeaguePage'];
export type SchemaLimit = components['schemas']['Limit'];
export type SchemaLimitKind = components['schemas']['LimitKind'];
export type SchemaLimitPage = components['schemas']['LimitPage'];
export type SchemaLimitPeriod = components['schemas']['LimitPeriod'];
export type SchemaLoginRequest = components['schemas']['LoginRequest'];
export type SchemaMarket = components['schemas']['Market'];
export type SchemaMarketComparison = components['schemas']['MarketComparison'];
export type SchemaMarketHeader = components['schemas']['MarketHeader'];
export type SchemaMarketStatus = components['schemas']['MarketStatus'];
export type SchemaMarketType = components['schemas']['MarketType'];
export type SchemaMoneyMinor = components['schemas']['MoneyMinor'];
export type SchemaOddsFormat = components['schemas']['OddsFormat'];
export type SchemaPageInfo = components['schemas']['PageInfo'];
export type SchemaPrice = components['schemas']['Price'];
export type SchemaProbability = components['schemas']['Probability'];
export type SchemaRefreshRequest = components['schemas']['RefreshRequest'];
export type SchemaRegisterRequest = components['schemas']['RegisterRequest'];
export type SchemaScore = components['schemas']['Score'];
export type SchemaSearchHit = components['schemas']['SearchHit'];
export type SchemaSearchPage = components['schemas']['SearchPage'];
export type SchemaSelection = components['schemas']['Selection'];
export type SchemaSelectionQuote = components['schemas']['SelectionQuote'];
export type SchemaSelectionRole = components['schemas']['SelectionRole'];
export type SchemaSessionResponse = components['schemas']['SessionResponse'];
export type SchemaSetLimitRequest = components['schemas']['SetLimitRequest'];
export type SchemaSlug = components['schemas']['Slug'];
export type SchemaSport = components['schemas']['Sport'];
export type SchemaSportPage = components['schemas']['SportPage'];
export type SchemaTotpCodeRequest = components['schemas']['TOTPCodeRequest'];
export type SchemaTotpEnrolment = components['schemas']['TOTPEnrolment'];
export type ResponseBadRequest = components['responses']['BadRequest'];
export type ResponseInternalError = components['responses']['InternalError'];
export type ResponseNotFound = components['responses']['NotFound'];
export type ResponseTooManyRequests = components['responses']['TooManyRequests'];
export type ResponseUnauthorized = components['responses']['Unauthorized'];
export type ResponseUnprocessableEntity = components['responses']['UnprocessableEntity'];
export type ParameterBookFilter = components['parameters']['BookFilter'];
export type ParameterCursor = components['parameters']['Cursor'];
export type ParameterEventId = components['parameters']['EventID'];
export type ParameterLeagueSlug = components['parameters']['LeagueSlug'];
export type ParameterMarketId = components['parameters']['MarketID'];
export type ParameterOddsFormatQuery = components['parameters']['OddsFormatQuery'];
export type ParameterPageLimit = components['parameters']['PageLimit'];
export type ParameterSelectionId = components['parameters']['SelectionID'];
export type ParameterSportSlug = components['parameters']['SportSlug'];
export type ParameterStartingBefore = components['parameters']['StartingBefore'];
export type $defs = Record<string, never>;
export interface operations {
    getAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getBalance: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The derived balances. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listLimits: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The limits in force. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    setLimit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLimitRequest"];
            };
        };
        responses: {
            /** @description The limit was recorded. Check `effective_from`. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Limit"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description A concurrent request already superseded the limit this one was based on. Retry. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    beginTOTPEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Enrolment started. Store the URI now; it is not returned again. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TOTPEnrolment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description A confirmed enrolment already exists. Remove it first. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    removeTOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPCodeRequest"];
            };
        };
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No enrolment to remove. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    confirmTOTPEnrolment: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TOTPCodeRequest"];
            };
        };
        responses: {
            /** @description Confirmed. The factor is now required at login. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description No enrolment in progress. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description Credentials rejected, or a second factor is required. Indistinguishable
             *     between "no such account" and "wrong password".
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /**
             * @description The account exists and the credentials are correct, but its status
             *     forbids a session -- `suspended`, `self_excluded` or `closed`. A
             *     self-excluded account cannot be logged into, which is the point of
             *     self-exclusion.
             */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The family is revoked (or was already). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Rotated. The previous refresh token is now dead. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description Unknown, expired, revoked or already-redeemed token. All four are
             *     reported identically.
             */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account was created and a session was opened. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description An account already exists for that address.
             *
             *     This endpoint DOES leak the existence of an address, and that is a
             *     deliberate, bounded trade: a registration form that accepts a
             *     duplicate silently is unusable, and the same fact is obtainable from
             *     any password-reset flow. `/auth/login` leaks nothing (see there).
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getBoard: {
        parameters: {
            query?: {
                /**
                 * @description Restrict prices to these books, by slug. Repeatable. Omitted means every
                 *     book. An unknown slug is a `400`, not a silent empty result -- a typo
                 *     that quietly returns nothing is the worst possible outcome for a price
                 *     comparison.
                 */
                book?: components["parameters"]["BookFilter"];
                /**
                 * @description Opaque continuation token from a previous response's `page.next_cursor`.
                 *     Do not construct or parse one. A cursor is bound to the ordering and the
                 *     filters it was minted under and is rejected `400` if presented with
                 *     different ones.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum rows in this page. */
                limit?: components["parameters"]["PageLimit"];
                /**
                 * @description Adds a rendered `display` string to every price. `decimal_odds` is always
                 *     present regardless, because it is the canonical value and the other two
                 *     formats are lossy.
                 */
                odds_format?: components["parameters"]["OddsFormatQuery"];
                /**
                 * @description Upper bound on `scheduled_start` (RFC 3339). Defaults to 24 hours from
                 *     the time the request is served, which is "today's board".
                 */
                starting_before?: components["parameters"]["StartingBefore"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the board. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listBooks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The books, by display name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPage"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getEvent: {
        parameters: {
            query?: {
                /**
                 * @description Restrict prices to these books, by slug. Repeatable. Omitted means every
                 *     book. An unknown slug is a `400`, not a silent empty result -- a typo
                 *     that quietly returns nothing is the worst possible outcome for a price
                 *     comparison.
                 */
                book?: components["parameters"]["BookFilter"];
                /**
                 * @description Adds a rendered `display` string to every price. `decimal_odds` is always
                 *     present regardless, because it is the canonical value and the other two
                 *     formats are lossy.
                 */
                odds_format?: components["parameters"]["OddsFormatQuery"];
            };
            header?: never;
            path: {
                eventId: components["parameters"]["EventID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event and its markets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventDetail"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getLeagueBoard: {
        parameters: {
            query?: {
                /**
                 * @description Restrict prices to these books, by slug. Repeatable. Omitted means every
                 *     book. An unknown slug is a `400`, not a silent empty result -- a typo
                 *     that quietly returns nothing is the worst possible outcome for a price
                 *     comparison.
                 */
                book?: components["parameters"]["BookFilter"];
                /**
                 * @description Opaque continuation token from a previous response's `page.next_cursor`.
                 *     Do not construct or parse one. A cursor is bound to the ordering and the
                 *     filters it was minted under and is rejected `400` if presented with
                 *     different ones.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum rows in this page. */
                limit?: components["parameters"]["PageLimit"];
                /**
                 * @description Adds a rendered `display` string to every price. `decimal_odds` is always
                 *     present regardless, because it is the canonical value and the other two
                 *     formats are lossy.
                 */
                odds_format?: components["parameters"]["OddsFormatQuery"];
                /**
                 * @description Upper bound on `scheduled_start` (RFC 3339). Defaults to 24 hours from
                 *     the time the request is served, which is "today's board".
                 */
                starting_before?: components["parameters"]["StartingBefore"];
            };
            header?: never;
            path: {
                leagueSlug: components["parameters"]["LeagueSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the league's board. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BoardPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    compareMarketPrices: {
        parameters: {
            query?: {
                /**
                 * @description Restrict prices to these books, by slug. Repeatable. Omitted means every
                 *     book. An unknown slug is a `400`, not a silent empty result -- a typo
                 *     that quietly returns nothing is the worst possible outcome for a price
                 *     comparison.
                 */
                book?: components["parameters"]["BookFilter"];
                /**
                 * @description Adds a rendered `display` string to every price. `decimal_odds` is always
                 *     present regardless, because it is the canonical value and the other two
                 *     formats are lossy.
                 */
                odds_format?: components["parameters"]["OddsFormatQuery"];
            };
            header?: never;
            path: {
                marketId: components["parameters"]["MarketID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The comparison grid. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MarketComparison"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    searchEvents: {
        parameters: {
            query: {
                /**
                 * @description Opaque continuation token from a previous response's `page.next_cursor`.
                 *     Do not construct or parse one. A cursor is bound to the ordering and the
                 *     filters it was minted under and is rejected `400` if presented with
                 *     different ones.
                 */
                cursor?: components["parameters"]["Cursor"];
                /** @description Maximum rows in this page. */
                limit?: components["parameters"]["PageLimit"];
                /**
                 * @description Competitor name prefix. Matched literally -- `%` and `_` are escaped
                 *     before the query, so a caller cannot turn a prefix search into a
                 *     leading-wildcard scan.
                 */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of matches. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    getSelectionHistory: {
        parameters: {
            query: {
                /**
                 * @description The book whose quotes to return, by slug. Required: a chart mixing
                 *     two books' quotes on one series is not a line movement chart, it is
                 *     two of them overlaid, and the caller must say which it wants.
                 */
                book: components["schemas"]["Slug"];
                /** @description Inclusive lower bound on `observed_at` (RFC 3339). */
                from: string;
                /** @description Reject (422) rather than truncate if the window would exceed this many points. */
                max_points?: number;
                /**
                 * @description Adds a rendered `display` string to every price. `decimal_odds` is always
                 *     present regardless, because it is the canonical value and the other two
                 *     formats are lossy.
                 */
                odds_format?: components["parameters"]["OddsFormatQuery"];
                /** @description Downsampling bucket width. `raw` returns stored quotes unaggregated. */
                resolution?: components["schemas"]["HistoryResolution"];
                /**
                 * @description Exclusive upper bound on `observed_at` (RFC 3339). Defaults to the
                 *     time the request is served. Half-open so adjacent windows tile
                 *     without double-counting the boundary quote.
                 */
                to?: string;
            };
            header?: never;
            path: {
                selectionId: components["parameters"]["SelectionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The line movement series. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySeries"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["UnprocessableEntity"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listSports: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The sports, by display name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SportPage"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
    listLeaguesInSport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sportSlug: components["parameters"]["SportSlug"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The leagues, by display name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaguePage"];
                };
            };
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["InternalError"];
        };
    };
}
