package auth

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/base64"
	"fmt"
	"strings"

	"github.com/anpl1623/sharpline/internal/domain"
)

// Identifier and token widths, in bytes of entropy before encoding.
const (
	// IDEntropyBytes is the entropy behind every identifier this package mints:
	// user ids, family ids, token ids, jti values.
	//
	// 16 bytes is 128 bits — the same budget as a UUIDv4 and, unlike a UUIDv4,
	// all of it random (a v4 spends 6 bits on the version and variant fields).
	// These identifiers are not secrets; they are only required to be
	// unguessable enough that an attacker cannot enumerate them and unique
	// enough that a collision never happens. At 128 bits the birthday bound is
	// ~2^64 identifiers, which this system will not reach.
	IDEntropyBytes = 16

	// TokenEntropyBytes is the entropy in a refresh token secret.
	//
	// migrations/00005 sets this floor and gives the reason the token is
	// SHA-256'd rather than argon2id'd: "unlike a password it is high-entropy
	// random bytes generated by us, so there is no dictionary to attack and no
	// reason to pay a memory-hard KDF on the hot refresh path. That reasoning
	// holds ONLY because the token is high-entropy -- phase 5 must generate it
	// from crypto/rand with at least 256 bits, never from a counter, a UUIDv4,
	// or a timestamp."
	//
	// So: 32 bytes, from crypto/rand, and the ONLY reason the cheap hash is
	// sound. Lowering this number silently makes the storage scheme wrong.
	TokenEntropyBytes = 32
)

// TokenHashLen is the width of a stored refresh-token digest. SHA-256, and
// refresh_tokens_hash_is_sha256 CHECKs octet_length(token_hash) = 32, so
// anything else is unstorable.
const TokenHashLen = sha256.Size

// b64id is the identifier and token encoding: URL-safe base64 without padding.
//
// The alphabet is [A-Za-z0-9-_], which is a strict subset of the charset every
// id column in migrations/00005 admits — `^[A-Za-z0-9._-]{1,128}$`, the same
// regex internal/domain's validID enforces. So an identifier minted here always
// satisfies users_id_charset, refresh_token_families_id_charset and
// refresh_tokens_id_charset, and NewOpaqueID cannot produce a value the
// database will reject.
//
// The colon is not in the alphabet, which is the property internal/domain
// singles out: CLAUDE.md §5 defines WebSocket channels as `event:{id}`, and an
// identifier containing a colon would make splitting a channel name ambiguous.
var b64id = base64.RawURLEncoding

// NewOpaqueID mints a random identifier with an optional prefix.
//
// The prefix is a readability affordance, not a namespace: `usr_` in front of a
// user id makes a log line and a support conversation legible, and costs
// nothing because '_' is in the permitted charset. It is validated so a caller
// cannot introduce a byte the database would refuse.
func NewOpaqueID(prefix string) (string, error) {
	if prefix != "" {
		for i := 0; i < len(prefix); i++ {
			c := prefix[i]
			ok := (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
				(c >= '0' && c <= '9') || c == '_' || c == '-' || c == '.'
			if !ok {
				return "", fmt.Errorf("%w: id prefix %q contains a byte outside [A-Za-z0-9._-]",
					ErrInvalid, sample(prefix))
			}
		}
	}

	buf := make([]byte, IDEntropyBytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("%w: reading identifier entropy: %w", ErrInternal, err)
	}

	var sb strings.Builder
	sb.Grow(len(prefix) + b64id.EncodedLen(IDEntropyBytes))
	sb.WriteString(prefix)
	sb.WriteString(b64id.EncodeToString(buf))
	id := sb.String()

	if len(id) > domain.MaxIDLen {
		return "", fmt.Errorf("%w: minted id is %d bytes, over the %d-byte column limit",
			ErrInvalid, len(id), domain.MaxIDLen)
	}
	return id, nil
}

// Identifier prefixes. Short, because they are prepended to every row's primary
// key and appear in every log line that mentions one.
const (
	userIDPrefix   = "usr_"
	familyIDPrefix = "fam_"
	tokenIDPrefix  = "rt_"
)

// NewUserID mints a user identifier.
func NewUserID() (domain.UserID, error) {
	s, err := NewOpaqueID(userIDPrefix)
	if err != nil {
		return "", err
	}
	// Round-tripped through the domain constructor rather than converted. The
	// charset argument above is a proof; this is the check that the proof is
	// still true after someone edits the alphabet.
	return domain.NewUserID(s)
}

// NewFamilyID mints a refresh-token family identifier.
func NewFamilyID() (string, error) { return NewOpaqueID(familyIDPrefix) }

// NewTokenID mints a refresh-token row identifier. migrations/00005 calls this
// column "the token's public identifier ... Safe to log. This is NOT the
// secret."
func NewTokenID() (string, error) { return NewOpaqueID(tokenIDPrefix) }

// NewRefreshTokenSecret mints the bearer half of a refresh token: 256 bits from
// crypto/rand, base64url-encoded.
//
// # Why the secret carries no identifier
//
// A common shape is `<token_id>.<secret>`, which lets the server look the row
// up by primary key. It is rejected here. The row is found by
// `WHERE token_hash = $1`, which refresh_tokens' UNIQUE constraint already
// indexes, so the id buys no lookup that is not already O(log n) — and it costs
// a probe oracle: an attacker submitting `rt_AAAA.junk` learns from the
// response whether that id exists.
//
// With a hash-only lookup there is nothing to probe. A wrong token hashes to a
// value that is in no index and the answer is [ErrTokenUnknown], with no
// distinction between "no such row" and "such a row, wrong secret" — because at
// 256 bits of entropy the second case does not occur.
func NewRefreshTokenSecret() (Secret, error) {
	buf := make([]byte, TokenEntropyBytes)
	if _, err := rand.Read(buf); err != nil {
		return Secret{}, fmt.Errorf("%w: reading refresh token entropy: %w", ErrInternal, err)
	}
	return NewSecret(b64id.EncodeToString(buf)), nil
}

// HashToken computes the value stored in refresh_tokens.token_hash: SHA-256 of
// the token's encoded form.
//
// Plain SHA-256 rather than argon2id, deliberately, and the justification is
// entirely dependent on [TokenEntropyBytes] — see its comment. A stretched hash
// on this path would add tens of milliseconds to every refresh for no security:
// there is no dictionary of 256-bit random strings to run.
//
// The digest is over the ENCODED string rather than the decoded bytes. Both are
// sound; the encoded form is chosen because it removes a decode step from the
// hot path and, more usefully, means a malformed token that is not valid base64
// still produces a well-formed digest that simply matches nothing — rather than
// an error branch that would need its own timing story.
func HashToken(token Secret) []byte {
	sum := sha256.Sum256([]byte(token.Expose()))
	return sum[:]
}
