// The gateway end to end: a real HTTP listener, a real WebSocket client, a real
// handshake, and market documents that were actually computed.
//
// # Where the fixtures come from
//
// Nothing in this file writes a price. [realMarkets] drives the REAL synthetic
// provider through the REAL normalizer and prices the result with the REAL
// pricing engine, which is the same path a record takes from a provider poll to
// price.computed — internal/pricing/synthetic_test.go established the pattern
// and this reuses it. What reaches a client here is therefore a document the
// pricer would actually publish, with margins, per-book bias and tick flooring
// all in play, rather than a plausible-looking literal.
//
// That matters more here than anywhere else in the package: this is the only
// file that asserts on what a BROWSER receives, and a hand-written payload would
// make it a test of this package's imagination.
package wsgw

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"

	"github.com/coder/websocket"
	"github.com/prometheus/client_golang/prometheus"

	"github.com/anpl1623/sharpline/internal/domain"
	"github.com/anpl1623/sharpline/internal/domain/odds"
	"github.com/anpl1623/sharpline/internal/ingest/normalizer"
	"github.com/anpl1623/sharpline/internal/ingest/provider"
	"github.com/anpl1623/sharpline/internal/ingest/provider/synthetic"
	"github.com/anpl1623/sharpline/internal/platform/kafka"
	"github.com/anpl1623/sharpline/internal/pricing"
)

// -----------------------------------------------------------------------------
// Real fixtures
// -----------------------------------------------------------------------------

// capturingNormalizerPublisher records what the normalizer would have put on
// odds.normalized. It stands in for the BUS and for no data: every record it
// captures was generated by the real adapter and mapped by the real mapper.
type capturingNormalizerPublisher struct {
	records []normalizer.NormalizedMarket
}

func (p *capturingNormalizerPublisher) PublishNormalized(_ context.Context, _ domain.MarketID, msg kafka.Message) error {
	if rec, ok := msg.Payload.(normalizer.NormalizedMarket); ok {
		p.records = append(p.records, rec)
	}
	return nil
}

// coldSnapshotter stands in for a compacted topic with nothing on it, which is
// the correct state for a normalizer that has never run.
type coldSnapshotter struct{}

func (coldSnapshotter) Read(context.Context, func(context.Context, *kafka.Delivery) error) (kafka.SnapshotStats, error) {
	return kafka.SnapshotStats{}, nil
}

// realMarkets returns priced markets computed from the synthetic feed, capped at
// limit so the test stays quick.
//
// The clock is fixed because the generator's determinism contract is stated over
// clock readings — "two adapters given the same seed and the same instants must
// produce byte-identical snapshots" — so this fixture is reproducible run to run.
func realMarkets(t *testing.T, limit int) []pricing.ComputedMarket {
	t.Helper()

	now := time.Date(2026, 8, 19, 19, 0, 0, 0, time.UTC)
	adapter, err := synthetic.New(synthetic.Options{
		Seed:  20260819,
		Clock: func() time.Time { return now },
	})
	if err != nil {
		t.Fatalf("synthetic.New: %v", err)
	}

	ctx := context.Background()
	cat, err := adapter.Catalogue(ctx)
	if err != nil {
		t.Fatalf("Catalogue: %v", err)
	}

	decoder, err := normalizer.NewNeutralDecoder(kafka.Provider(provider.NameSynthetic))
	if err != nil {
		t.Fatalf("NewNeutralDecoder: %v", err)
	}
	pub := &capturingNormalizerPublisher{}
	norm, err := normalizer.New(normalizer.Options{
		Provider:    kafka.Provider(provider.NameSynthetic),
		Decoder:     decoder,
		Producer:    pub,
		Snapshotter: coldSnapshotter{},
		Logger:      testLogger(),
		Clock:       func() time.Time { return now },
	})
	if err != nil {
		t.Fatalf("normalizer.New: %v", err)
	}

	for _, league := range cat.Leagues {
		snap, err := adapter.Fetch(ctx, provider.Scope{
			League:  league.ID(),
			Markets: []domain.MarketType{domain.MarketTypeMoneyline},
		})
		if err != nil {
			t.Fatalf("Fetch(%s): %v", league.ID(), err)
		}
		for _, ev := range snap.Events {
			if ev.Raw.IsZero() {
				continue
			}
			d := &kafka.Delivery{
				Topic:     kafka.TopicOddsRawPrefix + provider.NameSynthetic.String(),
				Key:       string(ev.Event.ID()),
				Timestamp: snap.FetchedAt,
				Envelope: kafka.Envelope{
					Version:    kafka.EnvelopeVersion,
					Type:       normalizer.RawMessageType,
					Producer:   "ingest",
					ProducedAt: snap.FetchedAt,
					ObservedAt: ev.Raw.ObservedAt,
					Data:       json.RawMessage(ev.Raw.Body),
				},
			}
			if err := norm.HandleMessage(ctx, d); err != nil {
				t.Fatalf("normalizer.HandleMessage: %v", err)
			}
		}
	}
	if len(pub.records) == 0 {
		t.Fatal("the synthetic feed produced no normalized markets; there is nothing to price")
	}

	// An empty preference list on purpose: the synthetic adapter DESIGNATES its
	// in-house book as the reference, and a market that prices at all is proof
	// that designation travelled the whole pipeline.
	engine, err := pricing.NewEngine(pricing.Options{DevigMethod: odds.MethodPower})
	if err != nil {
		t.Fatalf("pricing.NewEngine: %v", err)
	}

	out := make([]pricing.ComputedMarket, 0, limit)
	for _, rec := range pub.records {
		computed, err := engine.Price(ctx, rec)
		if err != nil {
			continue
		}
		if err := computed.Validate(); err != nil {
			t.Fatalf("the engine produced a record its own validator refuses: %v", err)
		}
		out = append(out, computed)
		if len(out) == limit {
			break
		}
	}
	if len(out) == 0 {
		t.Fatal("the engine refused every market on the synthetic feed")
	}
	return out
}

// -----------------------------------------------------------------------------
// Harness
// -----------------------------------------------------------------------------

// wsClient wraps a dialled connection with the decoding every test does.
type wsClient struct {
	t    *testing.T
	conn *websocket.Conn
}

func (c *wsClient) read(ctx context.Context) testFrame {
	c.t.Helper()
	typ, data, err := c.conn.Read(ctx)
	if err != nil {
		c.t.Fatalf("read: %v", err)
	}
	if typ != websocket.MessageText {
		c.t.Fatalf("server sent a %v frame; the protocol is JSON text", typ)
	}
	return decodeTestFrame(c.t, data)
}

func (c *wsClient) write(ctx context.Context, raw string) {
	c.t.Helper()
	if err := c.conn.Write(ctx, websocket.MessageText, []byte(raw)); err != nil {
		c.t.Fatalf("write: %v", err)
	}
}

// gateway builds a listener over a hub whose slate already holds the given
// markets, and returns the base URL.
func gateway(
	t *testing.T,
	markets []pricing.ComputedMarket,
	hubOpts func(*HubOptions),
	serverOpts func(*ServerOptions),
) (string, *Hub, *prometheus.Registry) {
	t.Helper()

	records := make([]*kafka.Delivery, 0, len(markets))
	for i, m := range markets {
		records = append(records, delivery(t, m, int64(i)))
	}
	source := newStubSource(records...)

	h, reg := newTestHub(t, func(o *HubOptions) {
		o.Source = source
		// A short drain by default so a test's teardown does not spend the
		// production budget waiting for a client that has already gone. Applied
		// before the caller's override, so a test about the drain can still set
		// its own.
		o.Options.ShutdownDrain = 25 * time.Millisecond
		if hubOpts != nil {
			hubOpts(o)
		}
	})

	runCtx, cancelRun := context.WithCancel(context.Background())
	runDone := make(chan struct{})
	go func() { defer close(runDone); _ = h.Run(runCtx) }()
	<-source.replay
	waitFor(t, func() bool { return h.Check(context.Background()) == nil })

	sopts := ServerOptions{Hub: h}
	if serverOpts != nil {
		serverOpts(&sopts)
	}
	srv, err := NewServer(sopts)
	if err != nil {
		t.Fatalf("NewServer: %v", err)
	}

	mux := http.NewServeMux()
	mux.Handle("GET "+Route, srv)
	ts := httptest.NewServer(mux)

	t.Cleanup(func() {
		shutdownCtx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
		defer cancel()
		_ = h.Shutdown(shutdownCtx)
		ts.Close()
		cancelRun()
		<-runDone
	})

	return ts.URL, h, reg
}

// dial opens a client connection the way a browser would: offering
// "sharpline.v1" and nothing else unless a credential is supplied.
func dial(t *testing.T, base, path string, opts *websocket.DialOptions) (*wsClient, *http.Response, error) {
	t.Helper()
	if opts == nil {
		opts = &websocket.DialOptions{Subprotocols: []string{Protocol}}
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	url := "ws" + strings.TrimPrefix(base, "http") + path
	conn, resp, err := websocket.Dial(ctx, url, opts)
	if err != nil {
		return nil, resp, err
	}
	t.Cleanup(func() { _ = conn.CloseNow() })
	return &wsClient{t: t, conn: conn}, resp, nil
}

// -----------------------------------------------------------------------------
// The happy path
// -----------------------------------------------------------------------------

func TestGatewayServesTheSnapshotThenDeltaProtocol(t *testing.T) {
	t.Parallel()

	markets := realMarkets(t, 4)
	base, h, _ := gateway(t, markets, nil, nil)

	client, _, err := dial(t, base, Route, nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	if got := client.conn.Subprotocol(); got != Protocol {
		t.Fatalf("negotiated subprotocol is %q, want %q — a bearer offer must never be "+
			"echoed back into the handshake response", got, Protocol)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	hello := client.read(ctx)
	if hello.Type != KindHello || hello.Seq != 1 {
		t.Fatalf("first frame is {%s seq %d}, want {hello seq 1}", hello.Type, hello.Seq)
	}
	if hello.Resumed {
		t.Fatal("a fresh anonymous connection claims a resumed session")
	}

	channels, err := ChannelsFor(markets[0])
	if err != nil {
		t.Fatalf("ChannelsFor: %v", err)
	}
	marketChannel := channels[0]

	client.write(ctx, fmt.Sprintf(`{"type":"subscribe","id":"s1","channels":[%q]}`, marketChannel.String()))

	ack := client.read(ctx)
	if ack.Type != KindAck || ack.ID != "s1" {
		t.Fatalf("second frame is {%s id %q}, want {ack s1}", ack.Type, ack.ID)
	}
	if len(ack.Rejected) != 0 {
		t.Fatalf("the ack rejected %+v", ack.Rejected)
	}

	snapshot := client.read(ctx)
	if snapshot.Type != KindSnapshot || snapshot.Channel != marketChannel.String() {
		t.Fatalf("third frame is {%s %s}, want a snapshot of %s",
			snapshot.Type, snapshot.Channel, marketChannel)
	}
	if len(snapshot.Markets) != 1 {
		t.Fatalf("the snapshot carries %d markets, want 1", len(snapshot.Markets))
	}

	// The payload reached the browser BYTE FOR BYTE. It is compared against the
	// bytes the slate holds rather than against a re-marshalling of the struct,
	// because a re-marshal would agree with a gateway that had quietly reshaped
	// the document.
	id, err := markets[0].MarketID()
	if err != nil {
		t.Fatalf("MarketID: %v", err)
	}
	held := h.Store().Snapshot(mustChannel(t, marketChannel.String()))
	if len(held) != 1 {
		t.Fatalf("the slate holds %d markets for %s, want 1", len(held), marketChannel)
	}
	if string(snapshot.Markets[0]) != string(held[0].Payload) {
		t.Fatal("the market document was re-marshalled on its way to the client")
	}

	var received pricing.ComputedMarket
	if err := json.Unmarshal(snapshot.Markets[0], &received); err != nil {
		t.Fatalf("the client received something that is not a ComputedMarket: %v", err)
	}
	if err := received.Validate(); err != nil {
		t.Fatalf("the client received a document that fails the pricer's own validator: %v", err)
	}
	if got, _ := received.MarketID(); got != id {
		t.Fatalf("the client received market %q, want %q", got, id)
	}
	if len(received.Books) == 0 || len(received.Fair.Selections) == 0 {
		t.Fatal("the delivered document has no books or no fair value; it did not come " +
			"from the pricing engine")
	}

	// A real price change, folded through the same handler the bus drives.
	moved := markets[0]
	moved.SourceFingerprint = "moved"
	moved.ObservedAt = moved.ObservedAt.Add(time.Second)
	moved.IngestedAt = moved.IngestedAt.Add(time.Second)
	if err := h.HandleMessage(ctx, delivery(t, moved, 999)); err != nil {
		t.Fatalf("HandleMessage: %v", err)
	}

	delta := client.read(ctx)
	if delta.Type != KindDelta || delta.Channel != marketChannel.String() {
		t.Fatalf("fourth frame is {%s %s}, want a delta on %s", delta.Type, delta.Channel, marketChannel)
	}
	if fingerprint(t, delta.Market) != "moved" {
		t.Fatal("the delta did not carry the updated document")
	}
	if delta.Seq != snapshot.Seq+1 {
		t.Fatalf("the delta carries seq %d after a snapshot at %d; the sequence must be "+
			"contiguous or a client cannot detect a gap", delta.Seq, snapshot.Seq)
	}

	// A client-requested resync re-bases the client on a fresh snapshot.
	client.write(ctx, `{"type":"resync","id":"r1"}`)
	again := client.read(ctx)
	if again.Type != KindSnapshot || again.ID != "r1" {
		t.Fatalf("resync answered with {%s id %q}, want {snapshot r1}", again.Type, again.ID)
	}
	if fingerprint(t, again.Markets[0]) != "moved" {
		t.Fatal("the resync snapshot carries a stale document")
	}
}

func TestAnonymousIsTheDefaultAndIsAnnouncedAsSuch(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), nil, nil)
	client, _, err := dial(t, base, Route, nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	var hello struct {
		Type          MessageKind `json:"type"`
		Authenticated bool        `json:"authenticated"`
		Protocol      string      `json:"protocol"`
		ConnectionID  string      `json:"connection_id"`
		Heartbeat     int         `json:"heartbeat_seconds"`
	}
	_, data, err := client.conn.Read(ctx)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if err := json.Unmarshal(data, &hello); err != nil {
		t.Fatalf("hello is not JSON: %v", err)
	}
	if hello.Type != KindHello || hello.Authenticated {
		t.Fatalf("hello = {%s authenticated:%v}; market data is public, so an anonymous "+
			"connection is a first-class state", hello.Type, hello.Authenticated)
	}
	if hello.Protocol != Protocol || hello.ConnectionID == "" || hello.Heartbeat <= 0 {
		t.Fatalf("hello is missing its own identity: %+v", hello)
	}
}

// -----------------------------------------------------------------------------
// Credentials (D5)
// -----------------------------------------------------------------------------

func TestATokenInTheQueryStringIsRefusedAndSaysWhy(t *testing.T) {
	t.Parallel()

	base, _, reg := gateway(t, realMarkets(t, 1), nil, nil)

	client, _, err := dial(t, base, Route+"?access_token="+sampleToken, nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// The refusal is delivered OVER THE SOCKET, because a browser can read a
	// close reason and can read essentially nothing from a failed handshake. A
	// silent downgrade to anonymous would let the developer watch market data
	// arrive and conclude the URL was fine.
	frame := client.read(ctx)
	if frame.Type != KindError || frame.Code != CodeUnauthorized {
		t.Fatalf("first frame is {%s %s}, want {error unauthorized}", frame.Type, frame.Code)
	}
	if frame.Seq != 1 {
		t.Fatalf("the refusal carries seq %d, want 1 — every frame on every connection "+
			"has a sequence number", frame.Seq)
	}

	_, _, err = client.conn.Read(ctx)
	if got := websocket.CloseStatus(err); got != websocket.StatusPolicyViolation {
		t.Fatalf("the connection closed with status %d, want %d", got, websocket.StatusPolicyViolation)
	}
	if n := counter(t, reg, "sharpline_ws_connections_total", "result", string(ConnectionRejected)); n != 1 {
		t.Fatalf("connections_total{rejected} = %v, want 1", n)
	}
	if n := counter(t, reg, "sharpline_ws_connections_total", "result", string(ConnectionAccepted)); n != 0 {
		t.Fatalf("connections_total{accepted} = %v; a refused credential is not an accepted "+
			"connection", n)
	}
}

func TestAPresentedTokenThatDoesNotVerifyClosesRatherThanDowngrades(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), func(o *HubOptions) {
		o.Options.Verifier = TokenVerifierFunc(func(context.Context, string) (Identity, error) {
			return Identity{}, ErrInvalidCredential
		})
	}, nil)

	client, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol, BearerSubprotocolPrefix + sampleToken},
	})
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	frame := client.read(ctx)
	if frame.Type != KindError || frame.Code != CodeUnauthorized {
		t.Fatalf("first frame is {%s %s}, want {error unauthorized} — a client that believes "+
			"it is authenticated and is quietly not is the failure this prevents",
			frame.Type, frame.Code)
	}
	_, _, err = client.conn.Read(ctx)
	if got := websocket.CloseStatus(err); got != websocket.StatusPolicyViolation {
		t.Fatalf("the connection closed with status %d, want %d", got, websocket.StatusPolicyViolation)
	}
}

func TestAVerifiedTokenIsAnnouncedInHello(t *testing.T) {
	t.Parallel()

	var seen string
	base, _, _ := gateway(t, realMarkets(t, 1), func(o *HubOptions) {
		o.Options.Verifier = TokenVerifierFunc(func(_ context.Context, token string) (Identity, error) {
			seen = token
			return Identity{UserID: "user-1", SessionID: "family-1", ExpiresAt: time.Now().Add(time.Hour)}, nil
		})
	}, nil)

	client, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol, BearerSubprotocolPrefix + sampleToken},
	})
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	var hello struct {
		Type          MessageKind `json:"type"`
		Authenticated bool        `json:"authenticated"`
		SessionID     string      `json:"session_id"`
	}
	_, data, err := client.conn.Read(ctx)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if err := json.Unmarshal(data, &hello); err != nil {
		t.Fatalf("hello is not JSON: %v", err)
	}
	if hello.Type != KindHello || !hello.Authenticated {
		t.Fatalf("hello = {%s authenticated:%v}, want an authenticated hello",
			hello.Type, hello.Authenticated)
	}
	if hello.SessionID != "family-1" {
		t.Fatalf("the durable session key is %q, want the token's own session claim", hello.SessionID)
	}
	if seen != sampleToken {
		t.Fatalf("the verifier was handed %q, want the raw token from the subprotocol offer", seen)
	}

	// The token itself must never appear in the handshake response.
	if got := client.conn.Subprotocol(); got != Protocol {
		t.Fatalf("the server echoed %q; echoing the bearer offer writes the client's access "+
			"token into a response header", got)
	}
}

func TestAnAuthorizationHeaderIsAcceptedForNonBrowserClients(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), func(o *HubOptions) {
		o.Options.Verifier = TokenVerifierFunc(func(context.Context, string) (Identity, error) {
			return Identity{UserID: "user-2", SessionID: "family-2"}, nil
		})
	}, nil)

	header := http.Header{}
	header.Set("Authorization", "Bearer "+sampleToken)
	client, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol},
		HTTPHeader:   header,
	})
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := client.read(ctx); frame.Type != KindHello {
		t.Fatalf("first frame is %s, want hello", frame.Type)
	}
}

func TestACredentialWithNoVerifierIsRefusedRatherThanIgnored(t *testing.T) {
	t.Parallel()

	// No Verifier configured. Anonymous still works, but a client that presents
	// a credential must not be silently served as anonymous — that is how a
	// deployment which forgot its signing key serves authenticated-looking
	// traffic to everybody.
	base, _, _ := gateway(t, realMarkets(t, 1), nil, nil)

	client, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol, BearerSubprotocolPrefix + sampleToken},
	})
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := client.read(ctx); frame.Type != KindError || frame.Code != CodeUnauthorized {
		t.Fatalf("first frame is {%s %s}, want {error unauthorized}", frame.Type, frame.Code)
	}
}

// -----------------------------------------------------------------------------
// The handshake
// -----------------------------------------------------------------------------

func TestAClientOfferingNoProtocolIsRefusedBeforeTheUpgrade(t *testing.T) {
	t.Parallel()

	base, _, reg := gateway(t, realMarkets(t, 1), nil, nil)

	_, resp, err := dial(t, base, Route, &websocket.DialOptions{})
	if err == nil {
		t.Fatal("a client that offered no subprotocol was upgraded; there is no default protocol")
	}
	if resp == nil || resp.StatusCode != http.StatusBadRequest {
		t.Fatalf("the refusal was %v, want 400", resp)
	}
	if n := counter(t, reg, "sharpline_ws_connections_total", "result", string(ConnectionRejected)); n != 1 {
		t.Fatalf("connections_total{rejected} = %v, want 1", n)
	}
}

func TestAnOriginFromAnotherHostIsRefused(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), nil, nil)

	header := http.Header{}
	header.Set("Origin", "https://evil.example")
	_, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol},
		HTTPHeader:   header,
	})
	// A WebSocket is not protected by CORS, so this check is the only control
	// there is: without it a page on any origin could open a socket here with
	// the user's cookies attached.
	if err == nil {
		t.Fatal("a cross-origin handshake was accepted")
	}
}

func TestAnAllowedOriginIsPermitted(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), nil, func(o *ServerOptions) {
		o.AllowedOrigins = []string{"trusted.example"}
	})

	header := http.Header{}
	header.Set("Origin", "https://trusted.example")
	client, _, err := dial(t, base, Route, &websocket.DialOptions{
		Subprotocols: []string{Protocol},
		HTTPHeader:   header,
	})
	if err != nil {
		t.Fatalf("an explicitly allowed origin was refused: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := client.read(ctx); frame.Type != KindHello {
		t.Fatalf("first frame is %s, want hello", frame.Type)
	}
}

func TestTheWildcardOriginIsRefusedAtConstruction(t *testing.T) {
	t.Parallel()

	h, _ := newTestHub(t, nil)
	_, err := NewServer(ServerOptions{Hub: h, AllowedOrigins: []string{"*"}})
	if err == nil {
		t.Fatal("NewServer accepted a wildcard origin")
	}
	if !errors.Is(err, ErrInvalidOptions) {
		t.Fatalf("error is %v, want ErrInvalidOptions", err)
	}
}

func TestTheConnectionCeilingRefusesWith503(t *testing.T) {
	t.Parallel()

	base, _, reg := gateway(t, realMarkets(t, 1), nil, func(o *ServerOptions) {
		o.MaxConnections = 1
	})

	first, _, err := dial(t, base, Route, nil)
	if err != nil {
		t.Fatalf("the first dial failed: %v", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := first.read(ctx); frame.Type != KindHello {
		t.Fatalf("first frame is %s, want hello", frame.Type)
	}

	_, resp, err := dial(t, base, Route, nil)
	if err == nil {
		t.Fatal("a second connection was accepted past the ceiling")
	}
	if resp == nil || resp.StatusCode != http.StatusServiceUnavailable {
		// 503 rather than an accept-then-close: a load balancer's passive health
		// check already understands a 503, and a client with a jittered backoff
		// would read a 1001 close as "try again shortly" rather than "full".
		t.Fatalf("the refusal was %v, want 503", resp)
	}
	if n := counter(t, reg, "sharpline_ws_connections_total", "result", string(ConnectionRejected)); n != 1 {
		t.Fatalf("connections_total{rejected} = %v, want 1", n)
	}
}

func TestAProtocolViolationOverARealSocketClosesTheConnection(t *testing.T) {
	t.Parallel()

	base, _, _ := gateway(t, realMarkets(t, 1), nil, nil)
	client, _, err := dial(t, base, Route, nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := client.read(ctx); frame.Type != KindHello {
		t.Fatalf("first frame is %s, want hello", frame.Type)
	}

	client.write(ctx, `{"type":"subscribe","channel":"market:x"}`)

	frame := client.read(ctx)
	if frame.Type != KindError || frame.Code != CodeMalformedFrame {
		t.Fatalf("frame is {%s %s}, want {error malformed_frame}", frame.Type, frame.Code)
	}
	_, _, err = client.conn.Read(ctx)
	if got := websocket.CloseStatus(err); got != websocket.StatusPolicyViolation {
		t.Fatalf("the connection closed with status %d, want %d", got, websocket.StatusPolicyViolation)
	}
}

func TestShutdownReachesARealClient(t *testing.T) {
	t.Parallel()

	base, h, _ := gateway(t, realMarkets(t, 1), func(o *HubOptions) {
		o.Options.ShutdownDrain = 50 * time.Millisecond
	}, nil)

	client, _, err := dial(t, base, Route, nil)
	if err != nil {
		t.Fatalf("dial: %v", err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if frame := client.read(ctx); frame.Type != KindHello {
		t.Fatalf("first frame is %s, want hello", frame.Type)
	}

	// Shutdown runs concurrently with the client's reads, which is the only
	// honest arrangement: it waits for each connection to finish, and a
	// connection cannot finish until the peer has received and acknowledged the
	// close frame. A test that called Shutdown and only then started reading
	// would be modelling a client that has stopped reading — which is a
	// different scenario, and the one the ctx budget and the straggler warning
	// exist for.
	shutdownCtx, shutdownCancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer shutdownCancel()
	shutdownErr := make(chan error, 1)
	go func() { shutdownErr <- h.Shutdown(shutdownCtx) }()

	frame := client.read(ctx)
	if frame.Type != KindError || frame.Code != CodeGoingAway {
		t.Fatalf("frame is {%s %s}, want {error going_away}", frame.Type, frame.Code)
	}
	_, _, err = client.conn.Read(ctx)
	if got := websocket.CloseStatus(err); got != websocket.StatusGoingAway {
		t.Fatalf("the connection closed with status %d, want %d", got, websocket.StatusGoingAway)
	}
	if err := <-shutdownErr; err != nil {
		t.Fatalf("Shutdown: %v", err)
	}
}
