package integration

import (
	"context"
	"reflect"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	"github.com/anpl1623/sharpline/internal/domain"
	"github.com/anpl1623/sharpline/internal/ingest/provider"
	"github.com/anpl1623/sharpline/pkg/client"
)

// The WebSocket gateway against real dependencies: a real Kafka broker, a real
// Redis, two real replicas of internal/wsgw, and pkg/client as the client.
//
// See wsgw_fixture_test.go for where the market documents come from. Nothing
// here is fabricated: every price a client receives below was generated by the
// synthetic market maker, published to a real raw topic, mapped by the real
// normalizer, priced by the real engine, and published to the real compacted
// price.computed topic.
//
// # Why these tests are not parallel
//
// Each one brings up one or two bus followers that replay the whole compacted
// topic, and several assert on exact metric deltas taken from a replica's own
// registry. Running them concurrently would make the replay contend for the
// broker and would leave "this publish produced exactly one pipeline-latency
// observation" unassertable, which is the point of the last test in the file.

// The snapshot is the fold of the compacted topic, and it must be exactly the
// markets that were published — no more, and none invented. The second half of
// this test is the one that is easiest to get wrong by accident: a channel with
// no markets must answer with an EMPTY snapshot, not with a missing one and not
// with a placeholder.
func TestASubscriptionReceivesASnapshotOfExactlyThePublishedMarkets(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 2, nil)
	onEvent := marketsOnEvent(markets, busiestEvent(markets))
	for _, m := range onEvent {
		s.publish(t, m)
	}

	node := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	channel := onEvent[0].eventChannel()
	node.awaitMarkets(t, channel, len(onEvent))

	// An event this slate never priced. It is a syntactically valid channel, so
	// the gateway must answer it — with nothing.
	emptyChannel := "event:" + uniqueID("evt")

	// All three of CLAUDE.md §5's channel kinds at once. A market is published on
	// its market, its event and its league channel, and one function decides that
	// set for both the publish path and the snapshot path — so a client holding
	// all three must see the same market in each, and a divergence here is the
	// hardest version of that bug to notice from a board.
	marketChannel := onEvent[0].marketChannel()
	leagueChannel := onEvent[0].leagueChannel()

	stream := dialStream(t, node, client.StreamOptions{
		Channels: []string{channel, marketChannel, leagueChannel, emptyChannel},
	})
	awaitStreamEvent(t, stream, client.StreamEventHello, 30*time.Second)

	populated := awaitSnapshot(t, stream, channel, 30*time.Second)
	if got, want := snapshotMarketIDs(t, populated), marketIDsOf(onEvent); !reflect.DeepEqual(got, want) {
		t.Errorf("snapshot of %s carried\n  %v\nwant\n  %v", channel, got, want)
	}

	if got, want := snapshotMarketIDs(t, awaitSnapshot(t, stream, marketChannel, 30*time.Second)),
		[]string{onEvent[0].ID.String()}; !reflect.DeepEqual(got, want) {
		t.Errorf("snapshot of %s carried %v, want %v", marketChannel, got, want)
	}
	// Only this slate's markets were published, and its league slug is namespaced
	// by its own provider, so the league channel is exactly the same set.
	if got, want := snapshotMarketIDs(t, awaitSnapshot(t, stream, leagueChannel, 30*time.Second)),
		marketIDsOf(onEvent); !reflect.DeepEqual(got, want) {
		t.Errorf("snapshot of %s carried\n  %v\nwant\n  %v", leagueChannel, got, want)
	}

	empty := awaitSnapshot(t, stream, emptyChannel, 30*time.Second)
	if empty.Markets == nil {
		t.Error("the empty snapshot arrived as a null markets field; an empty snapshot is a " +
			"correct answer and must be an empty array")
	}
	if len(empty.Markets) != 0 {
		t.Errorf("the snapshot of a channel nothing was published on carried %d markets",
			len(empty.Markets))
	}

	// The documents are the pricer's, byte for byte. Decoding one and finding it
	// is a computed market with the provenance the pipeline stamped is the
	// end-to-end statement that nothing here fabricated a price.
	assertComputedProvenance(t, populated.Markets[0], s.provider.String())
}

// A publish after the snapshot is a delta, and its sequence number is exactly
// one greater than the frame before it. That is the whole of D3: the number has
// to be dense for a gap in it to mean anything.
func TestASubsequentPublishArrivesAsADeltaWithTheNextSequenceNumber(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	first := s.generation(t, 1, nil)
	target := first[0]
	s.publish(t, target)

	node := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	channel := target.marketChannel()
	node.awaitMarkets(t, channel, 1)

	// The narrowest channel, so that nothing but this market's own movement can
	// land between the snapshot and the delta.
	stream := dialStream(t, node, client.StreamOptions{Channels: []string{channel}})
	snapshot := awaitSnapshot(t, stream, channel, 30*time.Second)
	if len(snapshot.Markets) != 1 {
		t.Fatalf("the snapshot of %s carried %d markets, want 1", channel, len(snapshot.Markets))
	}

	// A GENUINE line movement: the market maker's state is a function of time,
	// so moving the clock and polling again produces a different board rather
	// than the same one twice.
	s.advance(3 * time.Minute)
	byID := map[string]pricedMarket{string(target.ID): target}
	moved := s.generationFor(t, target.ID, byID)
	s.publish(t, moved)

	delta := awaitStreamEvent(t, stream, client.StreamEventDelta, 60*time.Second)
	if delta.Seq != snapshot.Seq+1 {
		t.Errorf("delta seq = %d, want %d (exactly one past the snapshot); a hole in the "+
			"sequence is what a client reads as lost frames", delta.Seq, snapshot.Seq+1)
	}
	if delta.Channel != channel {
		t.Errorf("delta channel = %q, want %q", delta.Channel, channel)
	}
	if delta.IsRemoval() {
		t.Error("an update arrived as a removal")
	}
	assertComputedProvenance(t, delta.Market, s.provider.String())
}

// A tombstone on the compacted topic means the market is gone for ever. A client
// that ignores one leaves it on the board permanently, because no further record
// for that key is coming — so it must arrive as a removal AND the market must
// leave the replica's slate.
func TestATombstoneArrivesAsARemovalAndLeavesTheSlate(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 1, nil)
	target := markets[0]
	s.publish(t, target)

	node := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	channel := target.marketChannel()
	node.awaitMarkets(t, channel, 1)

	stream := dialStream(t, node, client.StreamOptions{Channels: []string{channel}})
	awaitSnapshot(t, stream, channel, 30*time.Second)

	s.tombstone(t, target)

	removal := awaitStreamEvent(t, stream, client.StreamEventDelta, 60*time.Second)
	if !removal.IsRemoval() {
		t.Fatalf("the frame after the tombstone is not a removal: %+v", removal)
	}
	if removal.Removed != target.ID.String() {
		t.Errorf("removed = %q, want %q", removal.Removed, target.ID)
	}

	// The slate itself, not just the frame: a gateway that announced the removal
	// and kept the market would serve it to the next client to connect.
	node.awaitMarkets(t, channel, 0)

	if err := stream.Resync(t.Context(), channel); err != nil {
		t.Fatalf("Resync: %v", err)
	}
	after := awaitSnapshot(t, stream, channel, 30*time.Second)
	if len(after.Markets) != 0 {
		t.Errorf("a resynchronised snapshot still carries %d markets for a tombstoned market",
			len(after.Markets))
	}
}

// CLAUDE.md §9 requires `stream` to be horizontally scalable with NO session
// affinity, and D1 is how: every replica follows the compacted topic without a
// consumer group, so each one holds the whole slate rather than a partition of
// it. This is the assertion that says so — and it is the one that would fail
// loudly if the follower were ever changed to join a group.
func TestTwoReplicasBothHoldTheCompleteSlate(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 2, nil)
	onEvent := marketsOnEvent(markets, busiestEvent(markets))
	for _, m := range onEvent {
		s.publish(t, m)
	}

	channel := onEvent[0].eventChannel()
	want := marketIDsOf(onEvent)

	// Two replicas against ONE broker and ONE Redis. With a consumer group each
	// would hold roughly half the slate and a client would silently receive
	// nothing for the markets the other one owned.
	alpha := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	beta := newGatewayNode(t, bus, gatewayOptions{Redis: true})

	for _, node := range []*gatewayNode{alpha, beta} {
		node.awaitMarkets(t, channel, len(onEvent))

		stream := dialStream(t, node, client.StreamOptions{Channels: []string{channel}})
		snapshot := awaitSnapshot(t, stream, channel, 30*time.Second)
		if got := snapshotMarketIDs(t, snapshot); !reflect.DeepEqual(got, want) {
			t.Errorf("%s served\n  %v\nwant the complete slate\n  %v", node.replica, got, want)
		}
		if err := stream.Close(); err != nil {
			t.Errorf("%s: closing the stream: %v", node.replica, err)
		}
	}
}

// D6: the durable subscription set lives in Redis, so a client that reconnects
// and lands on a DIFFERENT replica gets its channels back without re-listing
// them. That is what makes affinity-free load balancing observable rather than
// merely claimed.
func TestAReconnectionOntoTheOtherReplicaRestoresTheChannelSet(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 1, nil)
	target := markets[0]
	s.publish(t, target)

	alpha := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	beta := newGatewayNode(t, bus, gatewayOptions{Redis: true})

	channel := target.eventChannel()
	alpha.awaitMarkets(t, channel, 1)
	beta.awaitMarkets(t, channel, 1)

	// One login family, presented to both replicas. The session id is what the
	// durable set is keyed by; the token is minted and verified by the real
	// pinned-algorithm issuer.
	user, err := domain.NewUserID(uniqueID("usr"))
	if err != nil {
		t.Fatalf("mint a user id: %v", err)
	}
	session := uniqueID("sess")
	token := alpha.token(t, user, session)

	firstConn := dialStream(t, alpha, client.StreamOptions{
		Token:    token,
		Channels: []string{channel},
	})
	hello := awaitStreamEvent(t, firstConn, client.StreamEventHello, 30*time.Second)
	if !hello.Hello.Authenticated {
		t.Fatal("the first connection is anonymous; the token did not verify")
	}
	if hello.Hello.Resumed {
		t.Error("the first connection reports a resumed session; nothing was stored yet")
	}
	awaitSnapshot(t, firstConn, channel, 30*time.Second)
	if err := firstConn.Close(); err != nil {
		t.Fatalf("closing the first connection: %v", err)
	}

	// The SECOND connection asks for NOTHING. Everything it receives came out of
	// Redis, put there by a connection served by another process.
	secondConn := dialStream(t, beta, client.StreamOptions{Token: token})
	resumed := awaitStreamEvent(t, secondConn, client.StreamEventHello, 30*time.Second)
	if !resumed.Hello.Resumed {
		t.Fatalf("the reconnection onto %s did not resume; hello = %+v", beta.replica, resumed.Hello)
	}
	if !containsChannel(resumed.Hello.Channels, channel) {
		t.Fatalf("restored channels = %v, want %s among them", resumed.Hello.Channels, channel)
	}

	snapshot := awaitSnapshot(t, secondConn, channel, 30*time.Second)
	if got, want := snapshotMarketIDs(t, snapshot), []string{target.ID.String()}; !reflect.DeepEqual(got, want) {
		t.Errorf("the resumed snapshot carried %v, want %v", got, want)
	}
}

// CLAUDE.md §5: "on overflow, drop the client's buffer and force a resync rather
// than letting one slow consumer apply backpressure to the entire hub."
//
// Both halves are asserted: the stalled client is counted and told to
// resynchronise, and the client beside it keeps receiving throughout.
func TestASlowConsumerIsDroppedAndResyncedWhileOthersKeepReceiving(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 1, nil)
	target := markets[0]
	s.publish(t, target)

	node := newGatewayNode(t, bus, gatewayOptions{Redis: true, SendQueueCapacity: 16})
	channel := target.marketChannel()
	node.awaitMarkets(t, channel, 1)

	// The STALLED client. Its own buffer is one frame deep and nothing ever
	// calls Next, so after the hello and the ack it stops reading the socket —
	// which is precisely the slow consumer the gateway is built to shed. The
	// SDK's own documentation makes this its deliberate failure mode: it would
	// rather become the slow consumer than drop a delta silently.
	stalled := dialStream(t, node, client.StreamOptions{
		Channels: []string{channel},
		Buffer:   1,
	})
	_ = stalled

	// The ACTIVE client, drained continuously by a goroutine.
	active := dialStream(t, node, client.StreamOptions{
		Channels: []string{channel},
		Buffer:   4096,
	})
	awaitSnapshot(t, active, channel, 30*time.Second)

	var (
		deltas atomic.Int64
		gaps   atomic.Int64
		drain  sync.WaitGroup
	)
	drainCtx, stopDrain := context.WithCancel(context.Background())
	drain.Add(1)
	go func() {
		defer drain.Done()
		for {
			ev, err := active.Next(drainCtx)
			if err != nil {
				return
			}
			switch ev.Kind {
			case client.StreamEventDelta:
				deltas.Add(1)
			case client.StreamEventGap, client.StreamEventResync:
				gaps.Add(1)
			}
		}
	}()
	defer func() {
		stopDrain()
		drain.Wait()
	}()

	// Republishing the same document is a real thing rather than a trick: the
	// pricer republishes a market when its configuration digest changes, and
	// internal/wsgw applies an equal observation instant deliberately — "the
	// worst case of applying it is one duplicate delta, against the far worse
	// case of suppressing a genuine change".
	dropped := func() float64 {
		return wsCounter(t, node.registry, "sharpline_ws_clients_dropped_total",
			map[string]string{"reason": "slow_consumer"})
	}

	deadline := time.Now().Add(90 * time.Second)
	for dropped() == 0 && time.Now().Before(deadline) {
		for i := 0; i < 40; i++ {
			s.publish(t, target)
		}
	}
	if dropped() == 0 {
		t.Fatalf("no client was dropped for slow consumption after flooding a stalled reader; "+
			"send queue depth was %d", 16)
	}

	if got := wsCounter(t, node.registry, "sharpline_ws_resyncs_total",
		map[string]string{"reason": "slow_consumer"}); got == 0 {
		t.Error("a buffer was discarded and no resync was counted; a client that is not told " +
			"has no way to recover")
	}
	if got := wsCounter(t, node.registry, "sharpline_ws_messages_sent_total",
		map[string]string{"kind": "resync"}); got == 0 {
		t.Error("no resync frame was enqueued for the dropped client")
	}

	// The active client kept receiving THROUGHOUT, which is the half of
	// CLAUDE.md §5 that says one slow consumer must not apply backpressure to
	// the hub.
	before := deltas.Load()
	for i := 0; i < 20; i++ {
		s.publish(t, target)
	}
	awaitTrue(t, 60*time.Second, "the active client kept receiving while another was dropped",
		func() bool { return deltas.Load() >= before+15 })

	if n := gaps.Load(); n != 0 {
		t.Errorf("the active client observed %d holes in its own stream; a stalled neighbour "+
			"must not cost it frames", n)
	}
	if err := active.Err(); err != nil {
		t.Errorf("the active stream ended: %v", err)
	}
}

// The headline SLO. deploy/observability's sharpline:odds_staleness_seconds:p50
// and :p99 panels have read "No data" since phase 0 waiting for stage="fanout",
// and this is the assertion that the gateway now supplies it.
//
// It also pins D7's OBSERVATION RULE, which is the part that is easy to get
// wrong in a way no dashboard would reveal: staleness is observed once per PRICE
// on the record and the pipeline latency once per RECORD, both once per fanout
// event — never once per subscriber. Two clients are subscribed here precisely
// so that "once per subscriber" would double the numbers and fail.
func TestFanoutObservesTheOddsStalenessSLOOncePerRecord(t *testing.T) {
	bus := newBusOptions(t)
	s := newSlate(t, bus, wsSlateOptions{})

	markets := s.generation(t, 1, nil)
	target := markets[0]
	s.publish(t, target)

	node := newGatewayNode(t, bus, gatewayOptions{Redis: true})
	channel := target.marketChannel()
	node.awaitMarkets(t, channel, 1)

	fanoutLabels := map[string]string{"stage": provider.StageFanout}
	pipelineLabels := map[string]string{"stage": provider.StageFanout}

	// Two subscribers on the SAME channel, so a per-subscriber observation would
	// be visible as a doubling.
	one := dialStream(t, node, client.StreamOptions{Channels: []string{channel}})
	awaitSnapshot(t, one, channel, 30*time.Second)
	two := dialStream(t, node, client.StreamOptions{Channels: []string{channel}})
	awaitSnapshot(t, two, channel, 30*time.Second)

	stalenessBefore, _ := histogramCount(t, node.registry, "sharpline_odds_staleness_seconds", fanoutLabels)
	pipelineBefore, _ := histogramCount(t, node.registry, "sharpline_pipeline_latency_seconds", pipelineLabels)

	s.advance(3 * time.Minute)
	byID := map[string]pricedMarket{string(target.ID): target}
	moved := s.generationFor(t, target.ID, byID)
	s.publish(t, moved)

	awaitStreamEvent(t, one, client.StreamEventDelta, 60*time.Second)
	awaitStreamEvent(t, two, client.StreamEventDelta, 60*time.Second)

	wantQuotes := uint64(quoteCount(moved))
	if wantQuotes == 0 {
		t.Fatal("the priced market carries no quote with an observation instant; there would be " +
			"nothing for the staleness SLO to measure")
	}

	awaitTrue(t, 30*time.Second, "the fanout staleness observation landed", func() bool {
		got, _ := histogramCount(t, node.registry, "sharpline_odds_staleness_seconds", fanoutLabels)
		return got >= stalenessBefore+wantQuotes
	})

	staleness, ok := histogramCount(t, node.registry, "sharpline_odds_staleness_seconds", fanoutLabels)
	if !ok {
		t.Fatalf("sharpline_odds_staleness_seconds{stage=%q} is not exported at all.\n"+
			"Histograms present:\n%s", provider.StageFanout, describeHistograms(t, node.registry))
	}
	if got := staleness - stalenessBefore; got != wantQuotes {
		t.Errorf("one delta to two subscribers produced %d staleness observations, want %d "+
			"(one per price on the record). Observing per subscriber would weight the headline "+
			"SLO by market popularity rather than by freshness.", got, wantQuotes)
	}

	pipeline, ok := histogramCount(t, node.registry, "sharpline_pipeline_latency_seconds", pipelineLabels)
	if !ok {
		t.Fatalf("sharpline_pipeline_latency_seconds{stage=%q} is not exported.\n"+
			"Histograms present:\n%s", provider.StageFanout, describeHistograms(t, node.registry))
	}
	if got := pipeline - pipelineBefore; got != 1 {
		t.Errorf("one delta to two subscribers produced %d pipeline-latency observations, want 1",
			got)
	}

	// The write-delay histogram is what keeps the two numbers above honest: they
	// are measured at the queue hand-off, and this is the gap between that and
	// the socket write actually happening.
	if got, exported := histogramCount(t, node.registry, "sharpline_ws_write_delay_seconds", nil); !exported || got == 0 {
		t.Errorf("sharpline_ws_write_delay_seconds has %d observations (exported=%v); without it "+
			"the distance between what the SLO measured and what the client received is assumed "+
			"rather than measured", got, exported)
	}
}
